name: Cloud Build AuraOS

on:
  push:
    branches: [ "**" ] # Срабатывает на любые пуши в любые ветки
  workflow_dispatch:   # Позволяет запустить сборку вручную кнопкой в браузере

jobs:
  build-os:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Скачивание репозитория
      uses: actions/checkout@v4

    - name: 🛠️ Установка системных утилит (lld, objcopy)
      run: |
        sudo apt update
        sudo apt install -y build-essential lld binutils-aarch64-linux-gnu

    - name: 📦 Настройка Rust и таргета ARM64
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-unknown-none

    - name: 🎨 Настройка Swift (Embedded)
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.0'

    - name: 🚀 Тестовая компиляция и вывод ошибок
      run: |
        mkdir -p build
        echo "=== ПРОВЕРКА ФАЙЛОВ В SYS_SERVICES ==="
        ls -la sys_services
        echo "======================================="
        
        echo "🎨 Запуск компилятора Swift напрямую..."
        # Запуск напрямую покажет, какие файлы конфликтуют или какие типы не найдены
        swiftc -target arm64-apple-none -O -parse-as-library -enable-experimental-feature EmbeddedSwift sys_services/*.swift -o build/services.o
